services:
  # Context.module.layer.class
  apiApp.Books.application.BookCreator:
    class: ../../../../Contexts/apiApp/Books/application/BookCreator
    arguments: ['@apiApp.Books.domain.BookRepository']

  apiApp.Books.application.BookFinder:
    class: ../../../../Contexts/apiApp/Books/application/BookFinder
    arguments: ['@apiApp.Books.domain.BookRepository']

  apiApp.Books.application.BookRemover:
    class: ../../../../Contexts/apiApp/Books/application/BookRemover
    arguments: ['@apiApp.Books.domain.BookRepository']

  apiApp.Books.domain.BookRepository:
    class: ../../../../Contexts/apiApp/Books/infraestructure/persistence/FileBookRepository
    arguments: ['']

