services:
  # HEALTH
  Apps.apiApp.controllers.health.GetStatusController:
    class: ../../controllers/health/GetStatusController
    arguments: []

  # AUTH
  Apps.apiApp.controllers.Auth.LoginController:
    class: ../../controllers/Auth/LoginController
    arguments: ['@apiApp.Auth.application.LoginUser']

  Apps.apiApp.controllers.Auth.RegisterController:
    class: ../../controllers/Auth/RegisterController
    arguments: ['@apiApp.Auth.application.RegisterUser']

  Apps.apiApp.controllers.Auth.ValidateMailController:
    class: ../../controllers/Auth/ValidateMailController
    arguments: ['@apiApp.Auth.application.ValidateMail']

  # AUTHORS
  Apps.apiApp.controllers.Authors.PostAuthorController:
    class: ../../controllers/Authors/PostAuthorController
    arguments: ['@apiApp.Authors.application.AuthorCreator']

  Apps.apiApp.controllers.Authors.GetAuthorController:
    class: ../../controllers/Authors/GetAuthorController
    arguments: ['@apiApp.Authors.application.AuthorFinder']

  Apps.apiApp.controllers.Authors.GetAllAuthorsController:
    class: ../../controllers/Authors/GetAllAuthorsController
    arguments: ['@apiApp.Authors.application.AllAuthorsFinder']

  Apps.apiApp.controllers.Authors.PatchAuthorController:
    class: ../../controllers/Authors/PatchAuthorController
    arguments: ['@apiApp.Authors.application.AuthorPatcher']

  Apps.apiApp.controllers.Authors.DeleteAuthorController:
    class: ../../controllers/Authors/DeleteAuthorController
    arguments: ['@apiApp.Authors.application.AuthorRemover']

  # BOOKS
  Apps.apiApp.controllers.Books.PostBookController:
    class: ../../controllers/Books/PostBookController
    arguments: ['@apiApp.Books.application.BookCreator']

  Apps.apiApp.controllers.Books.GetBookController:
    class: ../../controllers/Books/GetBookController
    arguments: ['@apiApp.Books.application.BookFinder']

  Apps.apiApp.controllers.Books.GetAllBooksController:
    class: ../../controllers/Books/GetAllBooksController
    arguments: ['@apiApp.Books.application.AllBooksFinder']

  Apps.apiApp.controllers.Books.PatchBookController:
    class: ../../controllers/Books/PatchBookController
    arguments: ['@apiApp.Books.application.BookPatcher']

  Apps.apiApp.controllers.Books.DeleteBookController:
    class: ../../controllers/Books/DeleteBookController
    arguments: ['@apiApp.Books.application.BookRemover']
