openapi: 3.0.3
info:
  title: ts-api
  description: |-
    This is a POC of an API/REST made with Typescript following DDD principles.

    Some usefull links:
    - [The Github Repository readme](https://github.com/vinjatovix/ts-api#readme)
    - [Contributing](https://github.com/vinjatovix/ts-api/blob/develop/CONTRIBUTING.md)
  contact:
    email: vinjadevix@gmail.com
  license:
    name: MIT License
    url: https://github.com/vinjatovix/ts-api/blob/develop/LICENSE.md
  version: '1.4.0'
servers:
  - url: HOST
    variables: {}
paths:
  /api/v1/Books:
    get:
      tags:
        - Books
      summary: Get All Books
      operationId: GetAllBooks
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

    post:
      tags:
        - Books
      summary: Create Book
      operationId: CreateBook
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            example:
              id: '{{$guid}}'
              title: '{{$randomWords}}'
              author: '{{$randomNamePrefix}} {{$randomLastName}}'
              isbn: '978-3-16-148410-0'
              releaseDate: '{{$isoTimestamp}}'
              pages: 1500
        required: true
      responses:
        '201':
          description: Created
          headers:
            vary:
              $ref: '#/components/headers/vary'
            access-control-allow-credentials:
              $ref: '#/components/headers/access-control-allow-credentials'
            x-xss-protection:
              $ref: '#/components/headers/x-xss-protection'
            x-content-type-options:
              $ref: '#/components/headers/x-content-type-options'
            x-frame-options:
              $ref: '#/components/headers/x-frame-options'
            date:
              $ref: '#/components/headers/date'
            content-length:
              $ref: '#/components/headers/content-length'
            x-envoy-upstream-service-time:
              $ref: '#/components/headers/x-envoy-upstream-service-time'
            server:
              $ref: '#/components/headers/server'

          content: {}
        '400':
          description: Bad Request
          headers:
            vary:
              $ref: '#/components/headers/vary'
            access-control-allow-credentials:
              $ref: '#/components/headers/access-control-allow-credentials'
            x-xss-protection:
              $ref: '#/components/headers/x-xss-protection'
            x-content-type-options:
              $ref: '#/components/headers/x-content-type-options'
            x-frame-options:
              $ref: '#/components/headers/x-frame-options'
            date:
              $ref: '#/components/headers/date'
            connection:
              $ref: '#/components/headers/connection'
            keep-alive:
              $ref: '#/components/headers/keep-alive'
            content-length:
              $ref: '#/components/headers/content-length'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
              example:
                message: <BookAuthor> <Beatae in delectus magnam dolorum enim praesentium dignissimos excepturi. Odit recusandae impedit. Unde nesciunt cumque nobis illo aut nihil voluptatem odio.> has more than 40 characters
        '422':
          description: Unprocessable Entity
          headers:
            vary:
              $ref: '#/components/headers/vary'
            access-control-allow-credentials:
              $ref: '#/components/headers/access-control-allow-credentials'
            x-xss-protection:
              $ref: '#/components/headers/x-xss-protection'
            x-content-type-options:
              $ref: '#/components/headers/x-content-type-options'
            x-frame-options:
              $ref: '#/components/headers/x-frame-options'
            date:
              $ref: '#/components/headers/date'
            connection:
              $ref: '#/components/headers/connection'
            keep-alive:
              $ref: '#/components/headers/keep-alive'
            content-length:
              $ref: '#/components/headers/content-length'
            etag:
              $ref: '#/components/headers/etag'

          content:
            application/json:
              schema:
                $ref: '#/components/schemas/422'
      deprecated: false
  /api/v1/Books/{id}:
    get:
      tags:
        - Books
      summary: Get Book by Id
      operationId: GetBookById
      parameters:
        - name: id
          in: path
          description: required
          required: true
          style: simple
          schema:
            type: string
            example: '{{bookId}}'
      responses:
        '200':
          description: Successful operation
          headers:
            vary:
              $ref: '#/components/headers/vary'
            access-control-allow-credentials:
              $ref: '#/components/headers/access-control-allow-credentials'
            x-xss-protection:
              $ref: '#/components/headers/x-xss-protection'
            x-content-type-options:
              $ref: '#/components/headers/x-content-type-options'
            x-frame-options:
              $ref: '#/components/headers/x-frame-options'
            date:
              $ref: '#/components/headers/date'
            content-length:
              $ref: '#/components/headers/content-length'
            etag:
              $ref: '#/components/headers/etag'
            x-envoy-upstream-service-time:
              $ref: '#/components/headers/x-envoy-upstream-service-time'
            server:
              $ref: '#/components/headers/server'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
      deprecated: false
    put:
      tags:
        - Books
      summary: Update Book by Id
      operationId: UpdateBook
      parameters:
        - name: id
          in: path
          description: required
          required: true
          style: simple
          schema:
            type: string
            example: '{{$guid}}'
      requestBody:
        description: ''
        content:
          application/json:
            example:
              id: '{{$guid}}'
              title: '{{$randomWords}}'
              author: '{{$randomNamePrefix}} {{$randomLastName}}'
              isbn: '978-3-16-148410-0'
              releaseDate: '{{$isoTimestamp}}'
              pages: 1500
        required: true
      responses:
        '200':
          description: Created
          headers:
            vary:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Origin
            access-control-allow-credentials:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'true'
            x-xss-protection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '0'
            x-content-type-options:
              content:
                text/plain:
                  schema:
                    type: string
                  example: nosniff
            x-frame-options:
              content:
                text/plain:
                  schema:
                    type: string
                  example: DENY
            date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Sun, 15 Oct 2023 19:19:00 GMT
            connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            keep-alive:
              content:
                text/plain:
                  schema:
                    type: string
                  example: timeout=5
            content-length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '0'
          content: {}
        '400':
          description: Bad Request
          headers:
            vary:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Origin
            access-control-allow-credentials:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'true'
            x-xss-protection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '0'
            x-content-type-options:
              content:
                text/plain:
                  schema:
                    type: string
                  example: nosniff
            x-frame-options:
              content:
                text/plain:
                  schema:
                    type: string
                  example: DENY
            content-length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '214'
            etag:
              content:
                text/plain:
                  schema:
                    type: string
                  example: W/"d6-UvcKv5g+ijEEpnLp3cngfhEGt+o"
            date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Sun, 15 Oct 2023 19:24:03 GMT
            connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            keep-alive:
              content:
                text/plain:
                  schema:
                    type: string
                  example: timeout=5
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
              example:
                message: <BookAuthor> <Beatae in delectus magnam dolorum enim praesentium dignissimos excepturi. Odit recusandae impedit. Unde nesciunt cumque nobis illo aut nihil voluptatem odio.> has more than 40 characters
        '422':
          description: Unprocessable Entity
          headers:
            vary:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Origin
            access-control-allow-credentials:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'true'
            x-xss-protection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '0'
            x-content-type-options:
              content:
                text/plain:
                  schema:
                    type: string
                  example: nosniff
            x-frame-options:
              content:
                text/plain:
                  schema:
                    type: string
                  example: DENY
            content-length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '263'
            etag:
              content:
                text/plain:
                  schema:
                    type: string
                  example: W/"107-1SWyRDyHUwHOAtJsyzyflhpva1k"
            date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Sun, 15 Oct 2023 19:23:47 GMT
            connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            keep-alive:
              content:
                text/plain:
                  schema:
                    type: string
                  example: timeout=5
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/422'
      deprecated: false
    delete:
      tags:
        - Books
      summary: Delete Book by Id
      operationId: DeleteBookById
      parameters:
        - name: id
          in: path
          description: required
          required: true
          style: simple
          schema:
            type: string
            example: '{{bookId}}'
      responses:
        '204':
          description: Deleted
          headers:
            vary:
              $ref: '#/components/headers/vary'
            access-control-allow-credentials:
              $ref: '#/components/headers/access-control-allow-credentials'
            x-xss-protection:
              $ref: '#/components/headers/x-xss-protection'
            x-content-type-options:
              $ref: '#/components/headers/x-content-type-options'
            x-frame-options:
              $ref: '#/components/headers/x-frame-options'
            date:
              $ref: '#/components/headers/date'
            connection:
              $ref: '#/components/headers/connection'
            keep-alive:
              $ref: '#/components/headers/keep-alive'
          content: {}
      deprecated: false
  /api/v1/health/http:
    get:
      tags:
        - Health
      summary: Api server
      operationId: Apiserver
      parameters: []
      responses:
        '200':
          description: OK
          headers:
            vary:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Origin
            access-control-allow-credentials:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'true'
            x-xss-protection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '0'
            x-content-type-options:
              content:
                text/plain:
                  schema:
                    type: string
                  example: nosniff
            x-frame-options:
              content:
                text/plain:
                  schema:
                    type: string
                  example: DENY
            content-length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '33'
            etag:
              content:
                text/plain:
                  schema:
                    type: string
                  example: W/"21-Rei14saXbyNBzYa963Az8GGsDLs"
            date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Sun, 15 Oct 2023 18:04:29 GMT
            connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            keep-alive:
              content:
                text/plain:
                  schema:
                    type: string
                  example: timeout=5
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
              example:
                version: 1.2.2
                status: OK
      deprecated: false
components:
  headers:
    connection:
      description: The connection header
      schema:
        type: string
        example: keep-alive
    keep-alive:
      description: The keep-alive header
      schema:
        type: string
        example: timeout=5
    vary:
      description: The vary header
      schema:
        type: string
      example: Origin
    access-control-allow-credentials:
      description: The access-control-allow-credentials header
      schema:
        type: string
      example: 'true'
    x-xss-protection:
      description: The x-xss-protection header
      schema:
        type: string
      example: '0'
    x-content-type-options:
      description: The x-content-type-options header
      schema:
        type: string
      example: nosniff
    x-frame-options:
      description: The x-frame-options header
      schema:
        type: string
      example: DENY
    date:
      description: The Date header
      schema:
        type: string
      example: Sun, 15 Oct 2023 19:19:00 GMT
    content-length:
      description: The content-length header
      schema:
        type: string
      example: '0'
    x-envoy-upstream-service-time:
      description: The X-Envoy-Upstream-Service-Time header
      schema:
        type: string
    server:
      description: The Server header
      schema:
        type: string
    etag:
      description: The ETag header
      schema:
        type: string
  schemas:
    Error:
      title: Error
      type: object
      properties:
        message:
          type: string
      example:
        id: 'Invalid value at params. Value: USB'
    422:
      title: validation error
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
          description: ''
      example:
        errors:
          - id: 'Invalid value at params. Value: USB'
          - author: 'Invalid value at body. Value: undefined'
          - isbn: 'Invalid value at body. Value: 522'
          - releaseDate: 'Invalid value at body. Value: leading-edge'
          - pages: 'Invalid value at body. Value: Baht'
    400:
      title: '400'
      type: object
      properties:
        message:
          type: string
      example:
        message: <BookAuthor> <Beatae in delectus magnam dolorum enim praesentium dignissimos excepturi. Odit recusandae impedit. Unde nesciunt cumque nobis illo aut nihil voluptatem odio.> has more than 40 characters
    Health:
      title: OK
      type: object
      properties:
        version:
          type: string
        status:
          type: string
      example:
        version: 1.2.2
        status: OK
    Book:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        author:
          type: string
        isbn:
          type: string
        releaseDate:
          type: string
        pages:
          type: number
      example:
        id: 'b1d9b21-f695-4abd-910b-78c42204f1f9'
        title: 'Book title'
        author: 'Mr. Cont'
        isbn: '978-3-16-148410-0'
        releaseDate: '2023-10-15T22:00:21.845Z'
        pages: 576
tags:
  - name: Books
  - name: Health
