imports:
  - { resource: ./application.yaml }

services:
  apiApp.EnvironmentArranger:
    class: ../../../../tests/Contexts/shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@apiApp.MongoClient']
