imports:
  - { resource: ./apps/application.yaml }
  - { resource: ./Auth/application.yaml }
  - { resource: ./Books/application.yaml }
  - { resource: ./Authors/application.yaml }
  - { resource: ./Characters/application.yaml }
  - { resource: ./Scenes/application.yaml }

