services:
  apiApp.MongoConfig:
    factory:
      class: ../../../../Contexts/shared/infrastructure/persistence/mongo/MongoConfigFactory
      method: 'createConfig'

  apiApp.MongoClient:
    factory:
      class: ../../../../Contexts/shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['apiApp', '@apiApp.MongoConfig']

  apiApp.Auth.domain.AuthRepository:
    class: ../../../../Contexts/apiApp/Auth/infrastructure/persistence/MongoAuthRepository
    arguments: ['@apiApp.MongoClient']

  plugin.Encrypter:
    class: ../../../../Contexts/shared/plugins/CryptAdapter
    arguments: []

  apiApp.Auth.application.LoginUser:
    class: ../../../../Contexts/apiApp/Auth/application/LoginUser
    arguments: ['@apiApp.Auth.domain.AuthRepository', '@plugin.Encrypter']

  apiApp.Auth.application.RegisterUser:
    class: ../../../../Contexts/apiApp/Auth/application/RegisterUser
    arguments: ['@apiApp.Auth.domain.AuthRepository', '@plugin.Encrypter']

  apiApp.Auth.application.ValidateMail:
    class: ../../../../Contexts/apiApp/Auth/application/ValidateMail
    arguments: ['@apiApp.Auth.domain.AuthRepository', '@plugin.Encrypter']

  apiApp.Auth.application.RefreshToken:
    class: ../../../../Contexts/apiApp/Auth/application/RefreshToken
    arguments: ['@plugin.Encrypter']
