name: Update README version

on:
  release:
    types:
      - released

jobs:
  update-readme-version:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Decrypt and import GPG key
      run: |
        gpg --import "${{ secrets.GPG_PRIVATE_KEY }}"

    - name: Change to the scripts directory
      run: cd scripts

    - name: Update README version
      run: bash update_readme_version.sh

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add README.md
        git commit -m 'Update version in README.md [skip ci]'
        git push origin HEAD:develop

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
