name: Update README version

on:
  release:
    types:
      - released

jobs:
  update-readme-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: v2 # Especifica la versión v2 para asegurar la compatibilidad con Node.js 16

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Change to the scripts directory
      run: cd scripts

    - name: Update README version
      run: bash update_readme_version.sh

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add README.md
        git commit -m 'Update version in README.md [skip ci]'
        git push
