name: Update README version

on:
  release:
    types:
      - released

jobs:
  update-readme-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update README version
      run: ./scripts/update_readme_version.sh  # Ejecuta el script

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add README.md
        git commit -m 'Update version in README.md [skip ci]'
        git push
